### ISSUE TITLE
dont work in 1.21

### ISSUE THREAD

**Issue by Chenyu550** [ViaVersionAddons/AxSmithing#10]
no response when clicking smithing table

**Comment by AverageGithub** [comment]
What version of the plugin are you using?

**Comment by Chenyu550** [comment]
> What version of the plugin are you using?

1.8

**Comment by AverageGithub** [comment]
You should update to 1.9 which was released a couple of hours ago

**Comment by Chenyu550** [comment]
> You should update to 1.9 which was released a couple of hours ago

i will try

**Comment by Chenyu550** [comment]
> You should update to 1.9 which was released a couple of hours ago

solved, thx
