### ISSUE TITLE
[Feature] Add Custom Font Support For a Resourcepack to overlay the custom GUI to revert it back to the older version

### ISSUE THREAD

**Issue by Coswics** [ViaVersionAddons/AxSmithing#3]
as the title says, I want to use a font (in a custom resourcepack) to overlay the old gui image but as is right now i'd have to add it to the default font file and that could get messy fast

**Comment by AverageGithub** [comment]
Hey, I'm not really a resource pack person, what would I need to change in order for this to work? You can change the tile of the GUI if that's what you'd like to do

**Comment by Coswics** [comment]
It would mostly be allowing a font field, i believe. putting things as the default font allows for users to copy the unicode and spam them in chat; whereas putting it in a separate font prevents that

**Comment by Coswics** [comment]
I found a fix. just gonna block it (unicode characters) in chat w/a diff plugin xP sorry for the troubles
