### ISSUE TITLE
[BUG] Item Deletion

### ISSUE THREAD

**Issue by Coswics** [ViaVersionAddons/AxSmithing#4]
Shift Clicking Into the Output Slot Deletes Items. This Behavior is also exhibited when shift clicking netherite ingots into the correct slot

https://github.com/ViaVersionAddons/AxSmithing/assets/142762002/1e51c247-2ad6-4060-b509-003bc64e168c

**Comment by AverageGithub** [comment]
Thanks for reporting! I will be working on a fix.

**Comment by AverageGithub** [comment]
Fixed in 1.4
