### ISSUE TITLE
[BUG] Doesnt Work On Older Versions?? (1.19.4 currently testing, and 1.19.2)

### ISSUE THREAD

**Issue by Coswics** [ViaVersionAddons/AxSmithing#5]
![image](https://github.com/ViaVersionAddons/AxSmithing/assets/142762002/2408dbf1-1a48-4f0b-acb5-e17d26318ebe)
config is as follows:

menu:
  # If your server version is 1.20+, this is what will be shown for lower version clients
  1_20:
    title: '&fꌕꌕꌕꌕꌕꌕꌕꌕ    骷 &f空&0 Upgrade Gear &f空'
    rows: 3
    template-slot: 26
    item-slot: 10
    upgrade-slot: 12
    output-slot: 14
    # If you need netherite upgrade template to convert a diamond item to netherite
    need-netherite-template: false
    # If we should force our gui instead of the default one, for 1.20 players.
    # Can be useful, if you want to remove the need for netherite template usage
    force-for-1_20-clients: false
    dont-convert-with-modeldata: false
    items:
      '1':
        slots:
        - 0-26
        material: light_gray_stained_glass_pane
      '2':
        slots:
        - 10
        - 12
        - 14
        - 26
        material: air
  
  # If your server version is 1.16+, this is what will be shown to 1.20+ clients
  1_16:
    title: '&fꌕꌕꌕꌕꌕꌕꌕꌕ    骷 &f空&0 Upgrade Gear &f空'
    rows: 3
    template-slot: 26
    item-slot: 10
    upgrade-slot: 12
    output-slot: 14
    # If you need netherite upgrade template to convert a diamond item to netherite
    need-netherite-template: false
    # If we should force our gui instead of the default one, for 1.20 players.
    # Can be useful, if you want to remove the need for netherite template usage
    force-for-1_20-clients: false
    dont-convert-with-modeldata: false
    items:
      '1':
        slots:
        - 0-26
        material: light_gray_stained_glass_pane
      '2':
        slots:
        - 10
        - 12
        - 14
        - 26
        material: air

**Comment by Coswics** [comment]
server versiion is 1.20.1; to note

**Comment by AverageGithub** [comment]
Hi, this config works for me, I'm not too sure on what could cause this. Could you try withe the new version?

**Comment by Coswics** [comment]
Tried With New Version, still the same results. Would any of these be causing interference? (some censored due to me kinda wanting to keep the server im having issues on private lol) and if it turns out one of them is causing issues we'll see
![dated](https://github.com/ViaVersionAddons/AxSmithing/assets/142762002/dd31b197-dfba-4c8e-8637-f54b5be7854a)

**Comment by AverageGithub** [comment]
That's interesting... Could you try it just with viaversion & viabackwards + this plugin?

**Comment by Coswics** [comment]
Tried it w/o the server specific stuff and it works. sigh. time to debug that plugin ig. thanks for your help regardless <3
Here's the Pack we made for it though! 
[AxSmithing Pack.zip](https://github.com/ViaVersionAddons/AxSmithing/files/13765583/AxSmithing.Pack.zip)

For Use With These Settings: 
  1_20:
    title: '&fꌕꌕꌕꌕꌕꌕꌕꌕ黑 &f骷&0Upgrade Gear'
    rows: 3
    template-slot: 14
    item-slot: 10
    upgrade-slot: 12
    output-slot: 17
    # If you need netherite upgrade template to convert a diamond item to netherite
    need-netherite-template: true
    # If we should force our gui instead of the default one, for 1.20 players.
    # Can be useful, if you want to remove the need for netherite template usage
    force-for-1_20-clients: false
    dont-convert-with-modeldata: false
    items:
      '1':
        slots:
        - 0-26
        material: structure_void
      '2':
        slots:
        - 10
        - 12
        - 14
        - 17
        material: air

**Comment by Coswics** [comment]
And Yes that pack is free to use if u wanna include that in the main description or something ;3
