### ISSUE TITLE
need-netherite-template boolean is not respected

### ISSUE THREAD

**Issue by Kichura** [ViaVersionAddons/AxSmithing#6]
When disabling the netherite template requirement in axsmithing's config, opening the smithing table still forces the player to include it just to perform the netherite upgrade despite it being set to disabled.

**Server infos:**

Paper = 1.20.4,
Client = 1.20.1,
Configs set in AxSmithing: `need-netherite-template: false` and `force-for-1_20-clients: true`.

**Comment by AverageGithub** [comment]
Fixed as of 1.6
